base_url = "https://mufeedvh.com"
title = "Mufeed VH"
description = "Mufeed VH's projects, blogs, security research, open source code, and stuff."
author = "Mufeed VH"

build_search_index = true
minify_html = false
default_language = "en"
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [
    { name = "tags", rss = true }
]

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[markdown]
highlight_code = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
