base_url = "https://www.mufeedvh.com"

title = "Mufeed VH"
description = "Mufeed VH's projects, blogs, security research, open source code, and stuff."

title_separator = "::"

compile_sass = true

build_search_index = false

check_external_links = true

theme = "sam"

minify_html = true

default_language = "en"

generate_feed = true
feed_filename = "rss.xml"

external_links_no_follow = true
external_links_no_referrer = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[markdown]
highlight_theme = "axar"
highlight_code = true

[extra]
home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "about", link = "/about" },
    { text = "projects", link = "/projects" },
    { text = "contact", link = "/contact" }
]

sam_bottom_menu = true

date_format = "%a %b %e, %Y"

show_word_count = true
show_reading_time = true
