base_url = "https://www.mufeedvh.com"
title = "Mufeed VH"
description = "Mufeed VH's projects, blogs, security research, open source code, and stuff."

build_search_index = true
check_external_links = true
minify_html = false
default_language = "en"
generate_feed = true
feed_filename = "rss.xml"
external_links_no_follow = true
external_links_no_referrer = true
taxonomies = [
    { name = "tags", rss = true }
]

[markdown]
highlight_code = false

[extra]
