image: archlinux
packages:
  - curl
  - rsync
sources:
  - https://github.com/janbaudisch/zola-sam
secrets:
  - b3e03761-91c2-4df1-b4ce-0ae980fa4579
  - 251ba7a6-aebe-4580-a8e0-714a6ffa1745
tasks:
  - setup: |
      curl -s https://paste.sr.ht/blob/a02ce97b659679a67e50c22da007e69ba26c3b13 | sh
  - build: |
      cd zola-sam
      zola build
  - deploy: |
      [ ! -e ~/deploy ] && exit 0
      cd zola-sam
      ~/deploy public zola-sam.janbaudisch.dev
